name: Build Modrinth Packs

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq & zip
        run: sudo apt-get update && sudo apt-get install -y jq zip

      - name: Build mrpacks
        run: |
          chmod +x build-mrpacks.sh
          ./build-mrpacks.sh

      - name: Create GitHub Release with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          NOTES=$(cat <<EOF
          - [CHANGELOG](https://github.com/unxok/ferncraft-mods/CHANGELOG.md) to find out what changed.
          - [GUIDE](https://github.com/unxok/ferncraft-mods/GUIDE.md) for help installing or updating your mod list.
          EOF
          )

          gh release create "$TAG_NAME" \
            Ferncraft.mrpack \
            SERVER-Ferncraft.mrpack \
            --title "Release $TAG_NAME" \
            --notes-file "$NOTES"
